### ISSUE TITLE
Are there options to force semicolons and braces?

### ISSUE THREAD

**Issue by jnvsor** [beautify-web/js-beautify#1064]
I would like to use js-beautify to enforce some code style. Specifically, I would like to force semicolons after statements and braces after ifs.

I can't find anything like that in js-beautify - does it exist?

**Comment by bitwiseman** [comment]
You want http://jshint.com/docs/options/ for that.

**Comment by jnvsor** [comment]
Yes but jshint doesn't offer to fix it for you does it? :)

**Comment by bitwiseman** [comment]
Fair point.  At this time, the beautifier is intended as a "whitespace-only reformatter".  This is due to design choices like #200, that make it safer to limit changes to whitespace and also limit the beautifier's ability to enforce rules.  It follows a best effort model, which is imperfect, but also means it will continue to work on a number case where strict parsing would choke.

**Comment by jnvsor** [comment]
Yes, every formatter I know of from sublime text to `php-cs-fixer` tends to choke on comments so I know it's no easy task, but I thought I'd ask anyway. Cheers!

**Comment by laggingreflex** [comment]
ESLint has a `--fix` option for many of its rules, including semicolons. http://eslint.org/docs/rules/semi

**Comment by bitwiseman** [comment]
@jnvsor  - Your original description doesn't mention comments.  Do you have other issues to file?
