### ISSUE TITLE
Script throws error after beautification

### ISSUE THREAD

**Issue by jsdeveloper97** [beautify-web/js-beautify#1207]
I am JavaScript beginner and I don't understand a lot of JavaScript code. However, while trying to deobfuscate a script from one website, I found JSBeautifier which is good for deobfuscating code and making code more readable. But, when I copied the part of script from that website into JSBeautifier, after beautifying code throws error. Original script doesn't throw error, but beautified one does.

I still have no idea what the script is supposed to do. I found it because I wanted to create a mod for a game (I found the script on [this](http://agar.io/) website), so I tried to understand and modify the script, but without success. I often use jsBeautifier to beautify the code so that it becomes easier to spot main parts of obfuscated code and possibly to understand whole script.

Ok, so this is the actual script, originaly copied from that website (earlier version):

# Input
```JavaScript
((g,...p)=>g[new((g=p)[-~[p]<<2](...g)[1])(p,g[0])])((...s)=>s[0](...s),a=>((_,i)=>new(Array)(1<<10).fill().map(k=>String.fromCharCode(34+(_+(_/=i)*~``+_)%i|0)).join``.replace(/\[|]/g,a=>'+!'[!!(a=>{try{return[eval(`[${a}`)][0]}catch(a){}})(a)|0]).replace(/"*$/,``))([...a].reduce((a,b,c)=>a+(b.charCodeAt(0)^c)*((a-3&572)^247),0),93),Function(`return this`)([+{}]),`;`,[[]][!{[-1]:{}}|0],(q,z,f,s,p,w)=>((w=w(m=q),((P,B,q)=>{q.d+={1:P?[P,B]:1}})+[f[~0]]).split(f[0]).map(v=>(s[s.map|[s]]=z)&&v).reduce((r,k,j,m)=>s[j-~!++j]=k.match(/\[.*?]/g).reduce((e,d)=>(m=[...d].length,w)(e,d.substring(1,m-1)),s[k.match(/^\d+/)|0]),-2),s),q=>(a,b)=>(b=>[(b,a)=>[f=>([a,b]=[b,a],a)[b].bind(a),y=>a[b]][-~typeof(a-b)]`${[b,a]=[a,b]}`,(...a)=>a[0][a[1]]][typeof[b[a],a[b]][2+~`[a,b]`]==(typeof[...a+`${b}`].reduce(...(z=>[z,z])((a=1)=>a=1)))|0](a,b))(Object.getOwnPropertyNames(a).find(a=>q(a)==b)));
```

# Expected Output
I am not sure how expected output should look like.

# Actual Output
```JavaScript
((g, ...p) => g[new((g = p)[-~[p] << 2](...g)[1])(p, g[0])])((...s) => s[0](...s), a => ((_, i) => new(Array)(1 << 10).fill().map(k => String.fromCharCode(34 + (_ + (_ /= i) * ~`` + _) % i | 0)).join ``.replace(/\[|]/g, a => '+!' [!!(a => {
  try {
    return [eval(`[${a}`)][0]
  } catch(a) {}
})(a) | 0]).replace(/"*$/, ``))([...a].reduce((a, b, c) => a + (b.charCodeAt(0) ^ c) * ((a - 3 & 572) ^ 247), 0), 93), Function(`return this`)([+{}]), `;`, [
  []
][!{
  [-1]: {}
} | 0], (q, z, f, s, p, w) => ((w = w(m = q), ((P, B, q) => {
  q.d += {
    1: P ? [P, B] : 1
  }
}) + [f[~0]]).split(f[0]).map(v => (s[s.map | [s]] = z) && v).reduce((r, k, j, m) => s[j - ~!++j] = k.match(/\[.*?]/g).reduce((e, d) => (m = [...d].length, w)(e, d.substring(1, m - 1)), s[k.match(/^\d+/) | 0]), -2), s), q => (a, b) => (b => [(b, a) => [f => ([a, b] = [b, a], a)[b].bind(a), y => a[b]][-~typeof(a - b)]
  `${[b,a]=[a,b]}`, (...a) => a[0][a[1]]
][typeof [b[a], a[b]][2 + ~`[a,b]`] == (typeof [...a + `${b}`].reduce(...(z => [z, z])((a = 1) => a = 1))) | 0](a, b))(Object.getOwnPropertyNames(a).find(a => q(a) == b)));
```

## Settings
```json
{
    "indent_size": 2,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": false,
    "max_preserve_newlines": 0,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse,preserve-inline",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": false,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0
}
```

# Explanation

When original script is compiled it works (though I still don't know what, but at least it doesn't throw error). But, when beautified it throws error

>Uncaught TypeError: Cannot read property '#\<Window\>' of undefined

I suppose that there is some issue with the way how jsBeautifier interprets the code. Maybe something should not be on new line or something similar. I am sure you are JavaScript experts and at least a lot better than me, so you can figure out what is interpreted wrongly in this script. Btw, I'm not expecting or insisting this to be fixed soon because I rarely use JavaScript, so I just spotted this code and I reported it, thats all.

P.S. sorry for bed english.

**Comment by bitwiseman** [comment]
@crveQQEklnxpSVvIimQ  Definitely a bug in the beautifier.  Thanks for reporting it.

**Comment by guest161373** [comment]
@crveQQEklnxpSVvIimQ It seems that the beautifier has nothing to do with the issue. After analyzing and debugging your script, I found that the problem is here

```JavaScript
1: P ? [P, B] : 1
```

The function which contains this code is stringified and after that, using regex, part between brackets are extracted as a string. So, **"P, B"** is extracted (in original script it is **"P,B"**). Then, all properties of global object (if you run it in a browser, it is **window**) are being put in an array and mapped to its hash strings (using function **q** from your script). Finally, global method (method of global object; i.e. property which is a function) which has hash **"P,B"** is called as a constructor.

Inspecting all possible combinations give you the result: hash of **"Proxy"** is **"P,B"** which means that your original script is equivalent to **"new window.Proxy(g, p)"**.

However, what the beautifier does is to beautify the code. It places a space before **"B"** and thus invalidate your hash, so the error is thrown because you're trying to call **"undefined"** as a constructor, because there is no such method of global object whose hash is **"P, B"**.

I suppose that the beautifier can't and shouldn't ever deal with these situations. JavaScript is an interpreter, so you'll always be able to obtain source code of the script and based on it throw or not throw an error. For example consider this code

```JavaScript
if((a=>a)+''!='a=>a')throw 0
```

It doesn't throw error, but after beautification it does. It stringifies a function and compare it to the expeted result. It is absolutelly impossible to cover these cases, because script itself will always be able to detect if it is beautified or not.

It would be great if you post exact link where you found this script, because on the link you provided has no such code. Your script looks like it does nothing but checking if the script itself is beautified or not, which doesn't make any sense.

**Comment by jsdeveloper97** [comment]
@bitwiseman 

I think @ghost is right, so whould we close this, since this is not a bug?
