### ISSUE TITLE
JSBeautify options for programmatic use?

### ISSUE THREAD

**Issue by ORESoftware** [beautify-web/js-beautify#1327]
With this code in mind:

```js
  context(b => {
        before(async h => {

            await driver.get('https://github.com/notifications');



        });
   });
```

I'd like to be able to remove excess blank lines. I looked at the readme, all the options are CLI options. **Where can I find the options for programmatic use instead of CLI use? I can't seem to find the docs for programmatic use.**

I asked this question on SO...https://stackoverflow.com/questions/48273979/js-beautify-programmatic-options-api

**Comment by bitwiseman** [comment]
Beautifier can remove blank lines between tokens using the `preserve_newlines: false` setting or limit the number of newlines using the `max_preserve_newlines` with a number value.

An example of API level usage is show in https://github.com/beautify-web/js-beautify#javascript .

The configuration option names are the same as the CLI names but with underscores instead of dashes.  

So to remove all empty lines: 
```
import {js_beautify} from 'js-beautify';

const originalCode = `
    const foo = 'bar';



    console.log(foo);
`)


const beautifiedCode = js_beautify(originalCode, { indent_size: 2, preserve_newlines: false})
```

**Comment by ORESoftware** [comment]
cool thank you
