### ISSUE TITLE
in the .vue file `space_after_anon_function` is invalid

### ISSUE THREAD

**Issue by hxkuc** [beautify-web/js-beautify#1425]
# Description
In the .vue file
set  
`'space_after_anon_function': true`

Example 1:
```
new Vue({
  name: 'myName',
  data() {
    // some value
  }
})
// Should look like
new Vue({
  name: 'myName',
  data () {
  }
})
```

Example 2:
```
async() => {}
// should look like
async () => {}
```

**Comment by bitwiseman** [comment]
@hxkuc @121595113 what should each of those inputs look like?

**Comment by hxkuc** [comment]
it shouid be this
```
new Vue({
  name: 'myName',
  data () {
  }
})
```
```
async () => {}
```

**Comment by 121595113** [comment]
and @bitwiseman 

```javascript
new Vue({
  data () {
   },
   name: 'myName',

})
```

should to be

```javascript
new Vue({
  data () {
  },
  name: 'myName',
})
```
Notice the alignment

**Comment by win7killer** [comment]
It's not about Vue.
Just like this:
```
let obj = {
    init() {
        // do something
    }
}
```
should be:
```
let obj = {
    init () {
        // do something
    }
}
```

**Comment by bitwiseman** [comment]
@win7killer @hxkuc @121595113 
I've reformatted this issue a bit.  I'm still unclear about how the expected behavior is supposed to work. 
To be specific: 
@121595113 The alignment is as you specified.  
@hxkuc Example 2 matches current output in 1.8.8 how should it change. 
@win7killer your example and @hxkuc Example 1 are not anon functions but rather some other thing.  Maybe `space_after_named_function` maybe?

**Comment by 121595113** [comment]
@bitwiseman `space_after_named_function` I agree

**Comment by bitwiseman** [comment]
@121595113  cool, so this is bug related to #608.
