### ISSUE TITLE
CSS new line just between selectors

### ISSUE THREAD

**Issue by sv2k** [beautify-web/js-beautify#1576]
# Input
With this new feature, when I give like this input: 
```
* {
    margin: auto;
    padding: 0;
    border: 0;
}
.container {
    position: relative;
    width: 100%;
    height: 100vh;
    display: block;
}
```

# Expected Output
I'd like to see this output:
```
* { margin: auto; padding: 0; border: 0; }
.container { position: relative; width: 100%; height: 100vh; display: block; }
```

**Comment by bitwiseman** [comment]
#1124

**Comment by PubliAlex** [comment]
Has been proposed long time ago, but it seems this kind of css formatting only interests old css wolf.... 

Milenials prefers to use the height of their wide screen because the right part of it is reserved for twitch streaming... 🥇 

Fortunately, jonshou saved us by releasing a [compact css extension](https://marketplace.visualstudio.com/items?itemName=jsonchou.css-compact)
