### ISSUE TITLE
Javascript multiline comments duplicates

### ISSUE THREAD

**Issue by D-AIRY** [beautify-web/js-beautify#1663]
# Description
Javascript multiline comments duplicates

# Input
The code looked like this before beautification:
```javascript
	/* comment
	
	*/

```

# Expected Output
The code should have looked like this after beautification:
```javascript
	/* comment
	
	*/

```

# Actual Output
The  code actually looked like this after beautification:
```javascript
	/* comment
	/* comment
	
	*/
	*/
```

# Steps to Reproduce
1. go to https://beautifier.io/
2. use following code with default options:
```
\t/* comment\n
\t\n
\t*/\n
```

## Environment
OS: windows 7

## Settings
Example:
```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": true,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse,preserve-inline",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0
}
```

**Comment by bitwiseman** [comment]
@D-AIRY 
I can't reproduce this issue.  Is the settings text above what was shown on the site? 
What browser are you using?

**Comment by D-AIRY** [comment]
Try this file: 
[bug.txt](https://github.com/beautify-web/js-beautify/files/3098973/bug.txt)
Ensure you have tab charated in lines 1-3 and empty line 4
Also reproducible with default settings.
Tested in latest firefox and ios safari

**Comment by bitwiseman** [comment]
@D-AIRY 
wow.  Great bug. Thanks!

**Comment by bitwiseman** [comment]
NOTES:

Also happens with:
```
 /* one space before each line
 
 */
```

The problem is that blank line is being turn into an empty string and passed to `print_token`. 

https://github.com/beautify-web/js-beautify/blob/d88c6a64620c3e795ff34344029e00941f1e297a/js/src/javascript/beautifier.js#L1372

In there we have this line: 

https://github.com/beautify-web/js-beautify/blob/d88c6a64620c3e795ff34344029e00941f1e297a/js/src/javascript/beautifier.js#L429

Which doesn't distinguish between empty string and null, but it should. 

This hasn't been run into more because usually blank lines get turned into empty lines.
