### ISSUE TITLE
Add basic smarty templating support

### ISSUE THREAD

**Issue by aswinkumar863** [beautify-web/js-beautify#1820]
I am using `js-beautify` to format[ `smarty` ](https://www.smarty.net/) files. It would be helpful if I can extend/modify the `Tokenizer` prototype. I've noticed that the module is not exported. Is there some other way to do it?

I am seeking for an API to extend the `Tokenizer` functions.

**Comment by bitwiseman** [comment]
@aswinkumar863 
It is intentionally not exported.  The api for this tools is intended to be just `beautify()` with input and options.  
This is partly because the Tokenizer is still new to this project (relatively speaking).  I did not design it for use outside this project and I certainly am not ready to support it as a stable public API.  Sorry.   

You are welcome to contribute to this project. If you want to add smarty templating support to this project, we only ask that you make your changes non-breaking to existing users and include tests to ensure future changes do not cause regressions.

Alternatively, you could fork or copy the code - it is MIT licensed. Of course, in that case you'd need to keep you fork up-to-date and so on.  

What functionality to do want to add?

**Comment by aswinkumar863** [comment]
@bitwiseman 
I am not adding any functionality. I am just trying to fix for https://github.com/aswinkumar863/smarty-vscode-support/issues/9

I tried forking initially. After the changes committed I installed in the project with this cmd.
```
npm install myusername/repo#branchName --save
```
But this approach failed because of the absence of `lib` folder and files. If I am not wrong, it is generated during installation (hot happened in my case). 

I think I can solve this problem by extending tokenizer or build using a webpack. Can I build with webpack? because I am not aware of `build.sh` files (my bad)

**Comment by bitwiseman** [comment]
@aswinkumar863  
You need to at least run `make js` on your fork.  If you commit the `lib` folder, then you might be able to run `npm install myusername/repo#branchName`.  But as I said that is not what I would suggest. 

Also, I looked at the changes [in your fork](https://github.com/beautify-web/js-beautify/compare/master...aswinkumar863:smarty-patches). I would suggest you make changes in [templatablepattern.js
](https://github.com/beautify-web/js-beautify/blob/master/js/src/core/templatablepattern.js) instead of adding the while loops.  That class handles template tokenizing for the entire beautifier.  Adding the smarty templating to it should get you exactly what you're looking for.

While that is not the way I would suggest implementing this

**Comment by bitwiseman** [comment]
To be clear, you should get the basic behavior you want if you take the start and end regular expressions you have [here](https://github.com/aswinkumar863/smarty-vscode-support/blob/725ba0b256248a74e439a4bb33f475645716e07c/client/src/language/formatter.ts#L32-L44) and integrate them into `templatablepattern.js`.  This would prevent smarty tags from getting mangled.

**Comment by aswinkumar863** [comment]
@bitwiseman I have added smarty to templating options, as you guided https://github.com/beautify-web/js-beautify/issues/1820#issuecomment-663183147 and aswinkumar863/smarty-vscode-support#84. Thank you for your kind guidance. Unfortunately, I am having 3 failed test cases, where `indent_handlebars = "true"` if I am not wrong handlebars gets conflicted with smarty because of `{` brace. Any help would be hugely appreciated. Thank you.

**Comment by aswinkumar863** [comment]
> @bitwiseman I have added smarty to templating options, as you guided [#1820 (comment)](https://github.com/beautify-web/js-beautify/issues/1820#issuecomment-663183147) and [aswinkumar863/smarty-vscode-support#84](https://github.com/aswinkumar863/smarty-vscode-support/issues/84). Thank you for your kind guidance. Unfortunately, I am having 3 failed test cases, where `indent_handlebars = "true"` if I am not wrong handlebars gets conflicted with smarty because of `{` brace. Any help would be hugely appreciated. Thank you.

@bitwiseman please look into the changes I have made in https://github.com/aswinkumar863/js-beautify/commit/15747529f5fc29889ebc53ba6badbd9b956e103a

**Comment by bitwiseman** [comment]
@aswinkumar863 
I made a couple comments on that commit, but I'd really prefer you create a PR and we can iterate on that.
