### ISSUE TITLE
in keyword in class method causes indentation problem

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#1846]
# Description

Class with a function named "in" causes indentation issue:

# Input
The code looked like this before beautification:
```
class {
  get a() {

  }

  in () {

  }

  b () {

  }
}
```

# Expected Output
The code should have looked like this after beautification:
```
(should be unchanged)
```

# Actual Output
The  code actually looked like this after beautification:
```
class {
    get a() {

        }

        in () {

        }

    b() {

    }
}
```

# Steps to Reproduce

Tried on https://beautifier.io/

**Comment by kcamsanc** [comment]
@bitwiseman Hi! I'm new to open source contributions and am considering addressing this issue. Before I take it though, I was wondering, is it still a requirement to ensure feature parity as described in [Contributions.md](https://github.com/beautify-web/js-beautify/blob/main/CONTRIBUTING.md)?

If so, what's the best way to reproduce this error in the Python implementation after forking and cloning the repo locally? Thanks.

**Comment by kcamsanc** [comment]
> If so, what's the best way to reproduce this error in the Python implementation after forking and cloning the repo locally? Thanks.

I believe I figured out the answer to my question above.

I am now working on this change. I will keep you all updated on my progress!

**Comment by kcamsanc** [comment]
Hi all, I just opened up PR #2004. Let me know what you think. There is one thing that I wanted to bring up though (also under "CURRENT DISCUSSION" in the PR):

- I'm under the impression that when I add unit tests to /test/data/*/test.js, corresponding tests are automatically generated for the Python implementation. Is this correct?
- If so, I found that my unit tests did not fail for the Python implementation before I made any changes to that implementation. However, I created a .js file myself, ran ./tools/python-dev js-beautify on my file, and found that the issue was actually reproducible in the Python implementation.
- How can I add unit tests for the Python implementation to incur a test failure before making changes to the Python implementation?

**Comment by bitwiseman** [comment]
> Hi all, I just opened up PR #2004. Let me know what you think. There is one thing that I wanted to bring up though (also under "CURRENT DISCUSSION" in the PR):
> 
> * I'm under the impression that when I add unit tests to `/test/data/*/test.js`, corresponding tests are automatically generated for the Python implementation. Is this correct?

Yes.

> * If so, I found that my unit tests did _not_ fail for the Python implementation before I made any changes to that implementation. However, I created a .js file myself, ran `./tools/python-dev js-beautify` on my file, and found that the issue was actually reproducible in the Python implementation.
> * How can I add unit tests for the Python implementation to incur a test failure before making changes to the Python implementation?

Did you run `make all`?  I'd be very surprised if that didn't generate the test for both js and python, and result in a failure in the python test run.

**Comment by kcamsanc** [comment]
> Did you run `make all`? I'd be very surprised if that didn't generate the test for both js and python, and result in a failure in the python test run.

Yes, to test this, I reverted my changes to `tokenizer.py` and ran both `make` and `make all` (not sure if there's a difference there). Neither resulted in a failure, and within the `make all` output, I do see: 
```
...
Test unpack() function. ... ok
test_detect (jsbeautifier.unpackers.tests.testurlencode.TestUrlencode)
Test detect() function. ... ok
test_unpack (jsbeautifier.unpackers.tests.testurlencode.TestUrlencode)
Test unpack function. ... ok

----------------------------------------------------------------------
Ran 36 tests in 0.056s
```
which I think means that no Python tests failed even after I reverted my changes in `tokenizer.py`. I also ran `make py`, which resulted in "PASSED". 

Looking into this further, I can actually see that my unit tests were automatically generated in`python/jsbeautifier/tests/generated/tests.py` like you said, so I feel like it's strange that no Python tests failed. FWIW, I know the JavaScript unit tests I wrote failed before I made changes to the JavaScript implementation. 

I know I can't make changes to `python/jsbeautifier/tests/generated/tests.py` as it is automatically generated. So, what's the best way to write good unit tests to make sure this bug doesn't reoccur in the future? (For now, like I mentioned, I've just had to run `./tools/python-dev js-beautify` on a local .js file I made to see if the bug is it present in the Python implementation.)
