### ISSUE TITLE
[CVE-2022-37609]/Prototype pollution found in options.js.

### ISSUE THREAD

**Issue by Supraja9726** [beautify-web/js-beautify#2106]
Prototype pollution vulnerability in beautify-web js-beautify 1.13.7 via the name variable in options.js.
The prototype pollution vulnerability can be mitigated with several best practices described here: https://learn.snyk.io/lessons/prototype-pollution/javascript/

**Comment by bitwiseman** [comment]
This report is incomplete to the point of useless.  Please reopen with specific line numbers or other details.

**Comment by highway2hell** [comment]
Possbile way to implement this prototype pollution is like below:

var beautify = require('js-beautify');
var beautify_js = require('js-beautify').js;
var javascriptCode = "function print() { console.log('hello')}"
 
const options = { indent_size: 2, space_in_empty_paren: true, js:{ indent_size:4 } }
console.log(beautify_js(javascriptCode,options))
 
//Apply the prototype pollution
options.js.__proto__.indent_size = 100
const options2 = {}
console.log(beautify_js(javascriptCode,options2))
 
Output 1:
function print() {
    console.log('hello')
}
 
Output after pollution:
function print() {
                                                                                                    console.log('hello')
}
 
As you can see that the second option don’t specify any indent_size, but the default indent_size has been change for every new option instance.
 
And the possbile fix for this is like:
function _mergeOpts(allOptions, childFieldName) {
  var finalOpts = {};
  **Object.freeze(finalOpts.__proto__);**
 
  allOptions = _normalizeOpts(allOptions);
  var name;
 
  for (name in allOptions) {
    if (name !== childFieldName) {
      finalOpts[name] = allOptions[name];
    }
  }
 
  //merge in the per type settings for the childFieldName
  if (childFieldName && allOptions[childFieldName]) {
    for (name in allOptions[childFieldName]) {
      console.log(childFieldName)
      finalOpts[name] = allOptions[childFieldName][name];
    }
  }
  return finalOpts;
}

**Comment by jackieju** [comment]
> Possbile way to implement this prototype pollution is like below:
> 
> var beautify = require('js-beautify'); var beautify_js = require('js-beautify').js; var javascriptCode = "function print() { console.log('hello')}"
> 
> const options = { indent_size: 2, space_in_empty_paren: true, js:{ indent_size:4 } } console.log(beautify_js(javascriptCode,options))
> 
> //Apply the prototype pollution options.js.**proto**.indent_size = 100 const options2 = {} console.log(beautify_js(javascriptCode,options2))
> 
> Output 1: function print() { console.log('hello') }
> 
> Output after pollution: function print() { console.log('hello') }
> 
> As you can see that the second option don’t specify any indent_size, but the default indent_size has been change for every new option instance.
> 
> And the possbile fix for this is like: function _mergeOpts(allOptions, childFieldName) { var finalOpts = {}; **Object.freeze(finalOpts.**proto**);**
> 
> allOptions = _normalizeOpts(allOptions); var name;
> 
> for (name in allOptions) { if (name !== childFieldName) { finalOpts[name] = allOptions[name]; } }
> 
> //merge in the per type settings for the childFieldName if (childFieldName && allOptions[childFieldName]) { for (name in allOptions[childFieldName]) { console.log(childFieldName) finalOpts[name] = allOptions[childFieldName][name]; } } return finalOpts; }

Nice catching.
But you actually freeze Object.__proto__. I suggest using Object.create(null), which will create an instance without __proto__.

e.g.

```
function _mergeOpts(allOptions, childFieldName) {

  var finalOpts = Object.create(null);
```

**Comment by zjhua2002** [comment]
@bitwiseman please kindly analyze [CVE-2022-37609](https://nvd.nist.gov/vuln/detail/CVE-2022-37609) which was reported recently with high Base Score: [9.8 CRITICAL] and provide assessments, thanks.

**Comment by jackieju** [comment]
The suspicious code identified as weakness is here, according to cve record:
https://github.com/beautify-web/js-beautify/blob/6fa891e982cc3d615eed9a1a20a4fc50721bff16/js/src/core/options.js#L167
Actually the suspicious code will not lead to object prototype pollution, because it's not recursive or deep copy of two object.
Only
a["_proto_"][x]=1 
will pollute.
But 
a["__proto__"]={x:1}
will not pollute.
Here is the simple test:
=== test1 ====
> a={}
{}
> a.{}proto{}.c=1
1
> b={}
{}
> b.c
1
==== test2 ====
> a2={}
{}
> a2.{}proto{}={c:1}
{ c: 1 }
>  b2={}
{}
> b2.c 
undefined
 
Above testing is passed in node.js and browser(chrome)
A merge function that can leads to prototype pollution must be recursive or cop depth >1.
e.g.
function merge(t,s){
    for (let k in s){
        if ( k in s && k in t)
{             // here do recursive copy              merge(t[k], s[k]);         }
else
{             t[k]=s[k];         }
    }
}
But that line of js_beautify code only do 1 level copy.
I modify js_beautify code to test, add code like below:
  var finalOpts = {};
  var a={};
  allOptions=JSON.parse('{"js":{"{}proto{}":{"role":"admin"}}, "aa":1, "{}proto{}":{"role":"admin"}}');
  
  allOptions = _normalizeOpts(allOptions);
  var name;
  for (name in allOptions) {
    if (name !== childFieldName)
{
      finalOpts[name] = allOptions[name];  // the suspicious line
  }
  }
    console.log("===>aa.role:"+a.role);
    
  //merge in the per type settings for the childFieldName
  if (childFieldName && allOptions[childFieldName]) {
    for (name in allOptions[childFieldName])
{       finalOpts[name] = allOptions[childFieldName][name];     }
  }
  console.log("===>a.role:"+aa.role);
In node.js and browser(Chrome), it cannot make the pollution happen.
So the suspicious code is safe. js-beautify should be innocent.

**Comment by meena-kaliswamy** [comment]
@bitwiseman I see that the tag (status: needs more info) has been removed, but the code has not been updated with @jackieju 's fix?

**Comment by bitwiseman** [comment]
@meena-kaliswamy 
If you read his commens, it says:

> Actually the suspicious code will not lead to object prototype pollution, because it's not recursive or deep copy of two object.

And since js-beautify doesn't do that, no update is needed.
