### ISSUE TITLE
Support comma first style of variable declaration

### ISSUE THREAD

**Issue by mrchief** [beautify-web/js-beautify#245]
Allow code to be formatted like this:

```
var a = 1
  , b = "somethign else"
  , isAwesome = true;
```

And apparently, we have a somewhat ready [patch](http://stackoverflow.com/questions/10872184/comma-first-js-formatter) available. Would be great if this can get included in here!

**Comment by olsonpm** [comment]
+1 for comma first support, and I agree with lewisdiamond's sentiment that ensuring tabs line up properly should not be the end goal as there are pragmatic reasons for the comma-first style.  I would love support for json as well.  Currently I have a hack in the global js-beautify code to do a lot of punctuation-first alternatives (for ternary operators was a must).

**Comment by bitwiseman** [comment]
To everyone who +1'd this: please take a look at branch `feature/comma-first` - https://github.com/beautify-web/js-beautify/commit/e5bfcf34b6089752e0a474e86ff533b46ac1677a

Tell me if this is a sufficient first step towards what you want that I should add it to the next release.

**Comment by bitwiseman** [comment]
@olsonpm, @lewisdiamond, @lukemartin, @mrchief - could you guys take a look at branch https://github.com/beautify-web/js-beautify/tree/feature/comma-first .

**Comment by olsonpm** [comment]
I will spend 30 minutes on it tonight and respond with thoughts.  Thanks for following up.

**Comment by olsonpm** [comment]
Got around to it this morning.  It all looks good to me due to your tests.  I have a personal branch with a lot of operator first functionality - I put my comma-first tests through your branch and they all passed no problem which is great news.

 - When I created my personal branch, I decided the comma-first operator would be passive, meaning the  following:

```
var a,
    b;
```

would not be changed.  You clearly stated this in the commit message, I just feel it's worth discussing with others what behavior they'd expect if they chose to use opt.comma_first.

Another thing, <Output>.previous_line and flags.previous_text are the same thing I believe, which was confusing to me at first but made sense in how you used it.

Other than that, the main difference between our implementations is that you opted to modify the previous line.  I was trying not to "go back and edit things" because I thought it was more confusing to develop.  Now your way is more concise than mine - it is easily read and you commented everything.  The existing code also edits previous tokens so your code is perfectly in line - honestly I'm just bringing it up because I'd like to know what your thoughts are.  In short, my opinion is that this program would be much easier to debug if tokens were only in charge of the white space ahead of them based on next tokens.

Thanks for addressing this!

**Comment by bitwiseman** [comment]
Forward-only is preferable. I looked at the hairball of how and where we decide what to do with/about commas, there are already places that we trim the output back to get them in the right place.  I decided to do something a little simplistic, get some tests in that verify the simplistic behavior and then see about tuning and refactor it later.

**Comment by olsonpm** [comment]
Sounds good.  I appreciate the feedback.

**Comment by bitwiseman** [comment]
And thank you very much for looking it over.  If you have any tests you want to add that would be a great help.
