### ISSUE TITLE
I want CSS Format maybe add not newline

### ISSUE THREAD

**Issue by iischajn** [beautify-web/js-beautify#330]
eg:

```
a{color: #666;cursor: pointer;}
```

any setting now?

**Comment by Alex360hd** [comment]
I reopen this because it's completly different than the minify action;

The minify action purpose is to have the smallest file size, to do that you remove all spaces and the stylesheet become unreadable.

I do web developpement since more than 10 years, and I find that the fact to write all property of css rule in one single line is a pleasure to read. For exemple :

    .btn-primary {
      background:#fff;
      color:#aaa;
      border:1px solid #aaa;
      border-radius:5px;
    }
    .btn-primary:hover {
      background:#000;
      color:#fff;
      border:1x solid #fff;
    }

Now with single line formatting :

    .btn-primary { background:#fff; color:#aaa; border:1px solid #aaa; border-radius:5px; }
    .btn-primary:hover { background:#000; color:#fff; border:1x solid #fff; }

Personnaly I find the second option easier to read than the first one and I like, as many developpers, to write code like this.

I discovered this way of styling using magento (that format it's css that way in the default theme) and I could not go back now I'm used to it.

**Comment by bitwiseman** [comment]
Reopened.  Not a priority, but I see the idea.
