### ISSUE TITLE
daisy-chain indentation leads to over-indentation

### ISSUE THREAD

**Issue by rasenplanscher** [beautify-web/js-beautify#482]
Using this via https://github.com/enginespot/js-beautify-sublime

Expected:

```
object
.foo()
.bar();
```

Actual:

```
object
  .foo()
  .bar();
```

To illustrate the problem: the current indenting can lead to EOFs like this:

```
      });
    });
})();
```

That looks like an error to me, and will prompt me to look for the cause &ndash; or worse, make me blind to the real ones =(

**Comment by arthur5005** [comment]
I have to +1 this request, this is especially handy when working with Promises.

```javascript
Promise.resolve()
.then(function() {
  return foo.bar()
})
.then(function() {
  return foo.baz();
});
```

This chaining can continue for a while, especially when writing a more involved api end point, and by the time you're looking at the bottom, you're constantly thrown off guard with how the indentation finishes relative to something close by.

I believe it's important that all closing indentation should be one level of depth difference from the next nearest.

**Comment by brandondrew** [comment]
:+1:

> I believe it's important that all closing indentation be one level of depth difference from the next nearest.

To me this is the clincher that proves that extra indentation is misleading and ultimately a mistake.  I realize some may feel that there is some sense in which 

```
Promise.resolve()
  .then(function() {
    return foo.bar()
  })
```

seems to reflect that the `then()` in some sense has a parent-child relationship with `Promise.resolve()`, but if that is true, then so does each subsequent `then()` have that relationship with the previous `then()`.  Of course there really is *no* such parent-child relationship, and indenting as if there were all the way down would make a grand mess, so no one does it.  But indenting the first `then()` just makes a *small* mess instead of a huge one—it's just that some people seem willing to put up with that small mess, while some of us prefer to not have *any* messes in our code if we can help it.

**Comment by brandondrew** [comment]
It may be nice to have the visual indication that indentation provides, but in this case it is overloading the meaning of indentation—not just indicating a new scope, but also indicating a chained method.  However we already have the `.` to indicate a chained method, and because the `.` is at the beginning of the text on the line, it really provides all the (pseudo-)indentation that is needed as long as you are paying attention to it.

So it's not *really* ***just*** a matter of personal preference—it's a matter of benefits & drawbacks of both approaches.  (Personal preference *is* of course involved, because some may not care about certain drawbacks or about certain benefits, but the discussion can be more fruitful if we discuss what those benefits and drawbacks *are*, rather than just saying "I prefer *x*" or "I prefer *y*".)

I think the case is strong that the drawbacks of extra indentation are significant, while the benefits can be had another way.

Drawbacks of extra indentation for chained methods:
* your indentation is no longer a reliable indicator of scope
* your closing punctuation is likely to make you think you've made a mistake

Benefits:
* you get a larger visual indication of method chaining than just a `.` by itself provides (BUT you *do* get that indication with just a `.`)

**Comment by Santinell** [comment]
+1

**Comment by klarkc** [comment]
+1 This is leading to `Expected exactly one space between '{a}' and '{b}'` errors in jslint.

**Comment by ilovett** [comment]
I would very much prefer to have this as an option, primarily to avoid unnecessary extra indentation in promise chaining:

```
  // fetch `config.json` and then set as constant
  $http.get('config.json').then(function(response) {
    angular.module('myApp').constant('CONFIG', response.data);
  })
  .then(function() {
    angular.bootstrap(document, ['myApp']);
  })
  .catch(function(err) {
    var message = (err && err.data || err && err.message);
    console.error('Unable to bootstrap application.', err);
    window.alert('Unable to bootstrap application.' + (message ? '\n\n' + message : ''));
  });
```

I think the extra indentation is the equivalent of:

```
try {
    // 4 spaces
  } // 2
  catch () {
    // 4
  }
```

I think it makes sense if the the child token which wraps around a block of indentation is on a new line from the initial variable:

```
  angular
    .module('module', function() {
      // .module starts on new line, so this block has 2 indents
    })
```

vs.

```
  angular.module('module', function() {
    // .module is on the same line as the initial variable angular, so this block has 1 indent
  })
```

But if it can all fit on one line then the double indentation shouldnt happen

**Comment by bitwiseman** [comment]
I've marked this as an enhancement.
I'm not arguing against it being a good idea, I just don't have time.
 
All you "+1"-ers and those who have commented, feel free to contribute a pull request.

**Comment by wonderbeyond** [comment]
+1 want

**Comment by aecepoglu** [comment]
I've opened a PR for this

https://github.com/beautify-web/js-beautify/pull/927

**Comment by pietrovismara** [comment]
+1 This is boring as hell
