### ISSUE TITLE
selector_separator_newline: true for Sass doesn't work

### ISSUE THREAD

**Issue by joseluisq** [beautify-web/js-beautify#563]
Hi, I'm using ST3 and `selector_separator_newline: true` for Sass doesn't work.

Now:

![](http://i.snag.gy/38HUh.jpg)

It should be like:

![](http://i.snag.gy/UP6sp.jpg)

**Comment by darlanalves** [comment]
This is about other config, called `newline_between_rules`. The latest version shipped with the "HTML-JS-CSS Prettify" plugin on ST3 don't have it, and causes the same problem. I've replaced the js-beautify folder under `plugin folder/scripts/node_modules` with a clone of this repo and it works. 

Check if adding `newline_between_rules: true` to your config solves the problem.

For the ST3 plugin, the issue is the current version of js-beautify published on npm, so a new version o npm to fix this is also necessary.

**Comment by joseluisq** [comment]
@darlanalves yes, it is solved by `newline_between_rules` at https://github.com/beautify-web/js-beautify/commit/44df1f123bb8b2934f4b29af114d1a7612ac5588
But, The current Js Beautify version is **1.5.4** and the commit that solves this (I suspect) will be released in the next **1.5.5** version.
