### ISSUE TITLE
ternary operations

### ISSUE THREAD

**Issue by cybermerlin** [beautify-web/js-beautify#670]
beautify format for ternary operations if line length more to wrap_line_length
```
var some = question
    ? value1
    : value2;
```

**Comment by alexjamesbrown** [comment]
+1

**Comment by alexjamesbrown** [comment]
although possible duplicate of #605

**Comment by olsonpm** [comment]
If either of you are interested, bitwiseman and I are discussing implementation on [this thread](https://github.com/beautify-web/js-beautify/pull/611#issuecomment-116768891).  Please join in if you have any input.

I only raise this because what began as 'ternary operations' newline placement is broadening out to all operators.  Right now we're hashing out which operators possibly belong on a newline.

**Comment by bitwiseman** [comment]
#735 added option to control this.

**Comment by alexjamesbrown** [comment]
cool! thanks
