### ISSUE TITLE
prevent

### ISSUE THREAD

**Issue by Danny-Engelman** [beautify-web/js-beautify#749]
The LinkedIN API requires this in the head

	<script type="text/javascript" src="//platform.linkedin.com/in.js">
		api_key: 729biipibhlozn
		onLoad: readyLinkedIN
		authorize: true
	</script>

But Beautify adds a space in the api key

	<script type="text/javascript" src="//platform.linkedin.com/in.js">
		api_key: 729 biipibhlozn
		onLoad: readyLinkedIN
		authorize: true
	</script>

Is there config option to prevent this?
tnx

**Comment by prettydiff** [comment]
The output looks correct.  The problem is that the provided text is parsed as JavaScript because it is inside a script tag instead of being parsed as HTML plain text content.  This content is, however, not syntactically valid JavaScript.  To be valid JavaScript these things should happen:

* The content should be wrapped in curly braces since it appears to be an object literal
* The items need to be comma separated
* The values need to be wrapped in quotes since they are probably string literals and not variable references
