### ISSUE TITLE
Breaks SSI code

### ISSUE THREAD

**Issue by ojemuyiwa** [beautify-web/js-beautify#750]
This plugin used on sublime text breaks SSI code e.g. 

`<a  href="<!--#echo var="CARURL"-->">login</a>`

becomes

`<a  href="<!--#echo var=" CARURL "-->">login</a>`

**Comment by prettydiff** [comment]
Your code sample seems faulty due to the quotes.  Instead consider this:

    <a href="">login</a>

**Comment by ojemuyiwa** [comment]
Nope SSI works just fine. Beautify puts spaces before VAR so added rule for
<!--# to ignore attributes totally

**Comment by prettydiff** [comment]
@ojemuyiwa Technically, your code works only because SSI is a syntax-limited Apache technology, which means the SSI tags are intercepted and parsed at the server during transmission before other services on the same system can access the file contents.  It isn't valid HTML/XML though and should expect to break anywhere outside of Apache's SSI parser.

**Comment by ojemuyiwa** [comment]
Yup totally agree.
