### ISSUE TITLE
Beautify CSS, support of shadowdom selectors?

### ISSUE THREAD

**Issue by arturparkhisenko** [beautify-web/js-beautify#805]
Like i reported there: https://github.com/Glavin001/atom-beautify/issues/658
Before beautify: `:host ::content` after beautify: `:host::content`. Maybe i can config that? It is standard CSS.

**Comment by bitwiseman** [comment]
Can you give a slightly larger example?  Also, helpful if you can provide link to some documentation for this notation.  We don't have a CSS expert on the project, so every issue is an education.

**Comment by ktiedt** [comment]
Chiming in because I am discussing this with someone now (this is now 1 revision old but it doesnt change the explanation) as stated here: http://www.w3.org/TR/2014/WD-css-scoping-1-20140403/#content-combinator
```
3.2.3 Selecting Shadow-Projected Content: the ::content pseudo-element
```

::content is a pseudo-element so essentially treated the same as a span or a div
so you would not write:
```
divspan {
   color: red;
}
```

And just to be thorough, :host is a pseudo-element that represents whatever web-component it is, so the above example could be read as equivalent to:
```
my-element div
```
where div the containing element of the "local DOM" being injected into the custom-elements shadow dom

Hope that helps!

Worth noting in the current draft: https://drafts.csswg.org/css-scoping/#content-combinator ::content is being renamed to ::slotted

**Comment by arturparkhisenko** [comment]
New change in Polymer 1.3.0 about:
```
