### ISSUE TITLE
not formatting html correctly

### ISSUE THREAD

**Issue by lesterjanpearson** [beautify-web/js-beautify#961]
my code is 

https://www.dropbox.com/s/iux7f5ijbrlg647/C__xampp_htdocs_devxsrv.com_exports_trest-1466985527_former-mexican-president-compares-trump-to-hilter.php%20%28sub%29%20-%20Sublime%20Text%20%28UNREGISTERED%29%202016-06-27%2009.24.49.png?dl=0

when i run:

js-beautify --type ["html"] --indent-size [4] /var/www/exports/testbeautnow.php > /var/www/exports/testbeautnowfix2.php 2>&1

it breaks the html into this

https://www.dropbox.com/s/v28p3zvhkjqv73q/C__xampp_htdocs_devxsrv.com_exports_testbeautnowfix2.php%20%28sub%29%20-%20Sublime%20Text%20%28UNREGISTERED%29%202016-06-27%2009.25.03.png?dl=0]

how do i fix this?

**Comment by prettydiff** [comment]
I am not sure what the error is, but it would really be helpful if you could upload the code samples as Gists.  That way somebody can analyze the code directly and attempt to reproduce the problem.  I would love to be able to play around with this so that I could advise whether there is something in your code causing a conflict, JS Beautify is just broken, or if there is some option setting causing a conflict.
